spring.application.name=sonoInteligenteSpring
spring.datasource.url=jdbc:postgresql://localhost:5432/sonointeligente_db
spring.datasource.username=postgres
spring.datasource.password=123

# JPA - Hibernate #
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
